# Generated by Django 5.1.2 on 2024-10-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
